// Code generated by MockGen. DO NOT EDIT.
// Source: version_service.go
//
// Generated by this command:
//
//	mockgen -source=version_service.go -destination=mocks/version_service_mock.go
//

// Package mock_versions is a generated GoMock package.
package mock_versions

import (
	reflect "reflect"

	model "github.com/jfrog/jfrog-cli-application/apptrust/model"
	service "github.com/jfrog/jfrog-cli-application/apptrust/service"
	gomock "go.uber.org/mock/gomock"
)

// MockVersionService is a mock of VersionService interface.
type MockVersionService struct {
	ctrl     *gomock.Controller
	recorder *MockVersionServiceMockRecorder
	isgomock struct{}
}

// MockVersionServiceMockRecorder is the mock recorder for MockVersionService.
type MockVersionServiceMockRecorder struct {
	mock *MockVersionService
}

// NewMockVersionService creates a new mock instance.
func NewMockVersionService(ctrl *gomock.Controller) *MockVersionService {
	mock := &MockVersionService{ctrl: ctrl}
	mock.recorder = &MockVersionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionService) EXPECT() *MockVersionServiceMockRecorder {
	return m.recorder
}

// CreateAppVersion mocks base method.
func (m *MockVersionService) CreateAppVersion(ctx service.Context, request *model.CreateAppVersionRequest, sync, dryRun bool, conflictResolution string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAppVersion", ctx, request, sync, dryRun, conflictResolution)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAppVersion indicates an expected call of CreateAppVersion.
func (mr *MockVersionServiceMockRecorder) CreateAppVersion(ctx, request, sync, dryRun, conflictResolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAppVersion", reflect.TypeOf((*MockVersionService)(nil).CreateAppVersion), ctx, request, sync, dryRun, conflictResolution)
}

// DeleteAppVersion mocks base method.
func (m *MockVersionService) DeleteAppVersion(ctx service.Context, applicationKey, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppVersion", ctx, applicationKey, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppVersion indicates an expected call of DeleteAppVersion.
func (mr *MockVersionServiceMockRecorder) DeleteAppVersion(ctx, applicationKey, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppVersion", reflect.TypeOf((*MockVersionService)(nil).DeleteAppVersion), ctx, applicationKey, version)
}

// DistributeAppVersion mocks base method.
func (m *MockVersionService) DistributeAppVersion(ctx service.Context, applicationKey, version string, request *model.DistributeAppVersionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeAppVersion", ctx, applicationKey, version, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeAppVersion indicates an expected call of DistributeAppVersion.
func (mr *MockVersionServiceMockRecorder) DistributeAppVersion(ctx, applicationKey, version, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeAppVersion", reflect.TypeOf((*MockVersionService)(nil).DistributeAppVersion), ctx, applicationKey, version, request)
}

// GetExportStatus mocks base method.
func (m *MockVersionService) GetExportStatus(ctx service.Context, applicationKey, version string) (*model.AppVersionExportStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExportStatus", ctx, applicationKey, version)
	ret0, _ := ret[0].(*model.AppVersionExportStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExportStatus indicates an expected call of GetExportStatus.
func (mr *MockVersionServiceMockRecorder) GetExportStatus(ctx, applicationKey, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExportStatus", reflect.TypeOf((*MockVersionService)(nil).GetExportStatus), ctx, applicationKey, version)
}

// ImportAppVersion mocks base method.
func (m *MockVersionService) ImportAppVersion(ctx service.Context, applicationKey, archivePath string, options *model.ImportAppVersionOptions) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportAppVersion", ctx, applicationKey, archivePath, options)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportAppVersion indicates an expected call of ImportAppVersion.
func (mr *MockVersionServiceMockRecorder) ImportAppVersion(ctx, applicationKey, archivePath, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportAppVersion", reflect.TypeOf((*MockVersionService)(nil).ImportAppVersion), ctx, applicationKey, archivePath, options)
}

// PromoteAppVersion mocks base method.
func (m *MockVersionService) PromoteAppVersion(ctx service.Context, applicationKey, version string, payload *model.PromoteAppVersionRequest, sync bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteAppVersion", ctx, applicationKey, version, payload, sync)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromoteAppVersion indicates an expected call of PromoteAppVersion.
func (mr *MockVersionServiceMockRecorder) PromoteAppVersion(ctx, applicationKey, version, payload, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteAppVersion", reflect.TypeOf((*MockVersionService)(nil).PromoteAppVersion), ctx, applicationKey, version, payload, sync)
}

// ReleaseAppVersion mocks base method.
func (m *MockVersionService) ReleaseAppVersion(ctx service.Context, applicationKey, version string, request *model.ReleaseAppVersionRequest, sync bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseAppVersion", ctx, applicationKey, version, request, sync)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseAppVersion indicates an expected call of ReleaseAppVersion.
func (mr *MockVersionServiceMockRecorder) ReleaseAppVersion(ctx, applicationKey, version, request, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAppVersion", reflect.TypeOf((*MockVersionService)(nil).ReleaseAppVersion), ctx, applicationKey, version, request, sync)
}

// RemoteDeleteAppVersion mocks base method.
func (m *MockVersionService) RemoteDeleteAppVersion(ctx service.Context, applicationKey, version string, request *model.RemoteDeleteAppVersionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteDeleteAppVersion", ctx, applicationKey, version, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoteDeleteAppVersion indicates an expected call of RemoteDeleteAppVersion.
func (mr *MockVersionServiceMockRecorder) RemoteDeleteAppVersion(ctx, applicationKey, version, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteDeleteAppVersion", reflect.TypeOf((*MockVersionService)(nil).RemoteDeleteAppVersion), ctx, applicationKey, version, request)
}

// RollbackAppVersion mocks base method.
func (m *MockVersionService) RollbackAppVersion(ctx service.Context, applicationKey, version string, request *model.RollbackAppVersionRequest, sync bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackAppVersion", ctx, applicationKey, version, request, sync)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollbackAppVersion indicates an expected call of RollbackAppVersion.
func (mr *MockVersionServiceMockRecorder) RollbackAppVersion(ctx, applicationKey, version, request, sync any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackAppVersion", reflect.TypeOf((*MockVersionService)(nil).RollbackAppVersion), ctx, applicationKey, version, request, sync)
}

// TriggerExport mocks base method.
func (m *MockVersionService) TriggerExport(ctx service.Context, applicationKey, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerExport", ctx, applicationKey, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerExport indicates an expected call of TriggerExport.
func (mr *MockVersionServiceMockRecorder) TriggerExport(ctx, applicationKey, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerExport", reflect.TypeOf((*MockVersionService)(nil).TriggerExport), ctx, applicationKey, version)
}

// UpdateAppVersion mocks base method.
func (m *MockVersionService) UpdateAppVersion(ctx service.Context, applicationKey, version string, request *model.UpdateAppVersionRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppVersion", ctx, applicationKey, version, request)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppVersion indicates an expected call of UpdateAppVersion.
func (mr *MockVersionServiceMockRecorder) UpdateAppVersion(ctx, applicationKey, version, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppVersion", reflect.TypeOf((*MockVersionService)(nil).UpdateAppVersion), ctx, applicationKey, version, request)
}

// UpdateAppVersionSources mocks base method.
func (m *MockVersionService) UpdateAppVersionSources(ctx service.Context, applicationKey, version string, request *model.UpdateVersionSourcesRequest, sync, dryRun, failFast bool) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAppVersionSources", ctx, applicationKey, version, request, sync, dryRun, failFast)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAppVersionSources indicates an expected call of UpdateAppVersionSources.
func (mr *MockVersionServiceMockRecorder) UpdateAppVersionSources(ctx, applicationKey, version, request, sync, dryRun, failFast any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAppVersionSources", reflect.TypeOf((*MockVersionService)(nil).UpdateAppVersionSources), ctx, applicationKey, version, request, sync, dryRun, failFast)
}
